import React from "react";
import Head from "next/head";
import Header from "../header/Header";

export default function Layout({ children }) {
  return (
    <Head>
      <title>investment</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </Head>
  );
}
