import Head from "next/head";
import { Inter } from "@next/font/google";
import Hero from "../components/homepage/hero/Hero";
import Description from "../components/homepage/description/Description";
import House from "../components/homepage/houses/House";
import Services from "../components/homepage/services/Services";
import Layout from "../components/UI/layout/Layout";
import Header from "../components/UI/header/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>investment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Description />
      <House />
      <Services />
    </>
  );
}
